name: FastAPI CI

on: [push, pull_request]  # Trigger the workflow on push or pull request

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4  
        with:
          python-version: '3.10'
          cache: 'pip'  

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Start FastAPI app
        run: |
          cd backend
          fastapi dev 
          sleep 10 

      - name: Check FastAPI /health endpoint
        run: |
          response=$(curl -s http://127.0.0.1:8000/health)
          echo "Response: $response"
          if [ "$response" == '{"status":"active"}' ]; then
            echo "Health check passed"
          else
            echo "Health check failed"
            exit 1
          fi

      - name: Kill FastAPI process
        run: |
          pkill -f "uvicorn main:app" 

      - name: Check process termination
        run: |
          pgrep -f "uvicorn main:app" || echo "Process terminated successfully" 
